### Test root path
GET https://nflprospectsapi.netlify.app/api/
x-api-key: ca108ce3a7ea5c67e5449a3f1211ba7e621741a6

### Test /api/v1 path
GET http://localhost:8888/api/v1
x-api-key: ca108ce3a7ea5c67e5449a3f1211ba7e621741a6

### Test /api/v1/positions endpoint
GET http://localhost:8888/api/v1/positions
x-api-key: ca108ce3a7ea5c67e5449a3f1211ba7e621741a6

### Test /api/v1/player endpoint with player_name
GET http://localhost:8888/api/v1/player?player_name=Travis_Hunter
x-api-key: ca108ce3a7ea5c67e5449a3f1211ba7e621741a6

### Test /api/v1/player endpoint with player_id
GET http://localhost:8888/api/v1/player?player_id=123
x-api-key: ca108ce3a7ea5c67e5449a3f1211ba7e621741a6

### Test /api/v1/player endpoint with college_id
GET http://localhost:8888/api/v1/player?college_id=5
x-api-key: ca108ce3a7ea5c67e5449a3f1211ba7e621741a6

### Test /api/v1/player endpoint with rank_less_than
GET http://localhost:8888/api/v1/player?rank_less_than=10
x-api-key: ca108ce3a7ea5c67e5449a3f1211ba7e621741a6

